[package]
name = "utils"
version = "0.1.0"
authors = ["Will Lunniss <willlunniss@gmail.com>"]
edition = "2021"

[dependencies]
strum = "0.23"
strum_macros = "0.23"
itertools = "0.10"
lazy_static = "1.4"
indoc = "1.0"
